// ********** THIS IS ACTION_TYPES FOR HOME_DATA ***********

export const GET_HOMEDATA_REQUEST="GET_HOMEDATA_REQUEST";
export const GET_HOMEDATA_SUCCESS="GET_HOMEDATA_SUCCESS";
export const GET_HOMEDATA_FAILURE="GET_HOMEDATA_FAILURE";

// ********** THIS IS ACTION_TYPES FOR HOME SIDE BARS ***********

export const GET_HOME_SIDEBAR_DATA_REQUEST="GET_HOME_SIDEBAR_DATA_REQUEST";
export const GET_HOME_SIDEBAR_DATA_SUCCESS="GET_HOME_SIDEBAR_DATA_SUCCESS";
export const GET_HOME_SIDEBAR_DATA_FAILURE="GET_HOME_SIDEBAR_DATA_FAILURE";